augmentations:
  - image_aug_ml.augmentation.affine.crop
  - image_aug_ml.augmentation.affine.rotate
  - image_aug_ml.augmentation.affine.translate
  - image_aug_ml.augmentation.affine.flip_vertical
  - image_aug_ml.augmentation.affine.flip_horizontal