# initialization args
initialization:
  # input image shape
  image_shape: [160, 160]

  # hidden layer sizes
  hl_sizes: [128, 256, 512, 728]

  # number of image classes
  num_classes: 10

# train args
train:
  epochs: 15
  learning_rate: 0.001
